# 1. What is NumPy?

NumPy is the fundamental library for numerical computing in Python. It provides a fast and efficient multidimensional array object along with mathematical functions optimized for data analysis.

# 2. Import NumPy

In [25]:
import numpy as np

print(np.__version__)

1.26.4


# 3. Create arrays from Python lists


One of the easiest ways to create a NumPy array is by converting a standard Python list.

NumPy arrays are more memory-efficient and support fast mathematical operations, making them the preferred data structure for data analysis.

In [26]:
import numpy as np

# Daily website visitors
daily_visitors = [245, 312, 298, 401, 389, 420, 375]

visitors_array = np.array(daily_visitors)

print(visitors_array)

[245 312 298 401 389 420 375]


The result is a one-dimensional NumPy array.

In [27]:
# Monthly revenue (thousands of €)

monthly_revenue = [18.5, 20.1, 21.8, 19.9]

revenue_array = np.array(monthly_revenue)

print(revenue_array)

[18.5 20.1 21.8 19.9]


NumPy automatically detects the appropriate data type.

In [28]:
# Sales of three stores during four months

sales = [
    [120, 135, 142, 150],
    [98, 110, 115, 123],
    [160, 158, 171, 180]
]

sales_array = np.array(sales)

print(sales_array)

[[120 135 142 150]
 [ 98 110 115 123]
 [160 158 171 180]]


This is a two-dimensional array (matrix).

In [29]:
# Sales by region, store and quarter

sales_3d = np.array([
    [
        [120, 130],
        [140, 150]
    ],
    [
        [160, 170],
        [180, 190]
    ]
])

print(sales_3d)

[[[120 130]
  [140 150]]

 [[160 170]
  [180 190]]]


### Summary

NumPy arrays can be created directly from Python lists.

Arrays can have:

- One dimension (vector)
- Two dimensions (matrix)
- Three or more dimensions

---

##  Practice Exercises

Complete the following exercises before moving to the next section.

### Exercise 1

Create a NumPy array containing the ages of eight employees.

In [30]:
# Write your solution here

### Exercise 2

Convert the following list of monthly expenses into a NumPy array.

expenses = [1250, 980, 1430, 1115, 1275, 1390]

In [31]:
# Write your solution here

### Exercise 3

Create a two-dimensional NumPy array representing the quarterly sales of four products.

In [32]:
# Write your solution here

###  Challenge

Create a three-dimensional array representing sales for:

- 2 stores
- 3 products
- 4 weeks

Fill it with your own values.

In [33]:
# Write your solution here

## Solutions

In [34]:
# Solution 1

import numpy as np

employee_ages = [24, 32, 61, 19, 54, 29, 45, 38]

employee_ages_array = np.array(employee_ages)

print(employee_ages_array)

[24 32 61 19 54 29 45 38]


In [ ]:
# Solution 2

expenses = [1250, 980, 1430, 1115, 1275, 1390]

expenses_array = np.array(expenses)

print(expenses_array)

[1250  980 1430 1115 1275 1390]


In [7]:
# Solution 3

sales = [
    [120, 135, 128, 142],
    [95, 110, 118, 125],
    [180, 175, 190, 200],
    [75, 82, 90, 96]
]

sales_array = np.array(sales)

print(sales_array)

[[120 135 128 142]
 [ 95 110 118 125]
 [180 175 190 200]
 [ 75  82  90  96]]


In [8]:
# Challenge Solution

weekly_sales = np.array([
    [
        [120, 130, 125, 140],
        [95, 100, 98, 105],
        [160, 170, 168, 175]
    ],
    [
        [110, 120, 118, 130],
        [90, 92, 96, 100],
        [150, 158, 162, 170]
    ]
])

print(weekly_sales)


[[[120 130 125 140]
  [ 95 100  98 105]
  [160 170 168 175]]

 [[110 120 118 130]
  [ 90  92  96 100]
  [150 158 162 170]]]


# 4. Create arrays with NumPy functions

NumPy provides several built-in functions to create arrays quickly without manually typing every value.

These functions are especially useful when working with large datasets, initializing matrices or generating sequences of numbers.


In [9]:
import numpy as np

# Create a 3x4 matrix filled with zeros

zeros_matrix = np.zeros((3, 4))

print(zeros_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


`np.zeros()` creates an array filled with zeros.

In [10]:
# Create a 2x5 matrix filled with ones

ones_matrix = np.ones((2, 5))

print(ones_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


`np.ones()` creates an array where every value is equal to one.

In [11]:
# Create a 3x3 matrix filled with the value 7

full_matrix = np.full((3, 3), 7)

print(full_matrix)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


`np.full()` fills the array with any value you choose.

In [12]:
import numpy as np

# Create a 4x4 identity matrix

identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Identity matrices are commonly used in linear algebra.

In [13]:
# Generate even numbers from 0 to 20

even_numbers = np.arange(0, 21, 2)

print(even_numbers)

[ 0  2  4  6  8 10 12 14 16 18 20]


`np.arange(start, stop, step)` creates an array of evenly spaced values.

In this example:

- `0` is the starting value.
- `21` is the stopping value (**not included**).
- `2` is the step, so only even numbers are generated.

> **Note:** Just like Python's `range()` function, the `stop` value is **excluded**. That's why `21` is not part of the resulting array, and the last value is `20`.

In [14]:
# Generate six equally spaced numbers between 0 and 100

values = np.linspace(0, 100, 6)

print(values)

[  0.  20.  40.  60.  80. 100.]


###  `np.arange()` vs `np.linspace()`

Although both functions generate sequences of numbers, they are used in different situations.

| Function | Best used when... |
|----------|-------------------|
| `np.arange()` | You know the **step size** between values. |
| `np.linspace()` | You know the **exact number of values** you want to generate. |

**Example:**

- `np.arange(0, 10, 2)` → Creates numbers every **2 units**.
- `np.linspace(0, 10, 6)` → Creates **6 equally spaced values** between 0 and 10.

---

## Practice Exercises

### Exercise 1

Create a 5×5 matrix filled with zeros.

In [ ]:
# Write your solution here

### Exercise 2

Create a 3×4 matrix filled with ones.

In [ ]:
# Write your solution here

### Exercise 3

Create a 4×4 matrix where every value is 100.

In [ ]:
# Write your solution here

### Exercise 4

Generate the numbers from 5 to 50 with a step of 5.

In [ ]:
# Write your solution here

### Exercise 5

Generate 8 equally spaced numbers between 10 and 50.

In [ ]:
# Write your solution here

###  Challenge

A company wants to simulate customer IDs.

Create an array containing IDs from 1000 to 1100 with an increment of 5.


## Solutions



In [35]:
# Solution 1

zeros_matrix = np.zeros((5, 5))

print(zeros_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
# Solution 2

ones_matrix = np.ones((3, 4))

print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [38]:
# Solution 3

full_matrix = np.full((4, 4), 100)

print(full_matrix)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [41]:
# Solution 4

numbers = np.arange(5, 51, 5)

print(numbers)

[ 5 10 15 20 25 30 35 40 45 50]


In [42]:
# Solution 5

values = np.linspace(10, 50, 8)

print(values)

[10.         15.71428571 21.42857143 27.14285714 32.85714286 38.57142857
 44.28571429 50.        ]


In [43]:
# Challenge Solution

costumer_ids = np.arange(1000, 1001, 5)

print(costumer_ids)

[1000]


# 5. Random arrays

NumPy provides several functions to generate random values.

Random arrays are commonly used to simulate data, test algorithms and create sample datasets for analysis.

In [46]:
import numpy as np

# Set a random seed for reproducibility

np.random.seed(42)

Using a random seed ensures that the same random numbers are generated every time the code is executed.

In [49]:
# Generate five random numbers between 0 and 1

random_values = np.random.rand(5)

print(random_values)

[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]


In [51]:
# Generate ten random customer IDs between 1000 and 9999

customer_ids = np.random.randint(1000, 10000, size=10)

print(customer_ids)

[1189 3734 4005 5658 2899 8734 2267 2528 4556 4890]


In [52]:
# Generate a 3x4 matrix with random integers

sales = np.random.randint(100, 500, size=(3, 4))

print(sales)

[[234 120 428 266]
 [373 487 188 415]
 [113 341 364 445]]


In [53]:
# Randomly select products

products = np.array([
    "Laptop",
    "Tablet",
    "Smartphone",
    "Monitor",
    "Keyboard"
])

selected_products = np.random.choice(products, size=3)

print(selected_products)

['Keyboard' 'Tablet' 'Monitor']


---

## Practice Exercises

### Exercise 1

Generate 8 random integers between 1 and 100.

In [ ]:
# Write your solution here

### Exercise 2

Create a 4×4 matrix with random integers between 10 and 99.

In [ ]:
# Write your solution here

### Exercise 3

Generate 6 random decimal numbers between 0 and 1.

In [ ]:
# Write your solution here

### Exercise 4

Randomly select 5 cities from the following list:

- Madrid
- Paris
- London
- Rome
- Berlin
- Lisbon

In [ ]:
# Write your solution here

### Challenge 

Generate a dataset representing the daily sales of 30 days.

The sales should be random integers between €500 and €2000.

## Solutions


In [57]:
# Solution 1

random_integers = np.random.randint(1, 101, size=8)

print(random_integers)

[50  4  2  6 54  4 54 93]


In [2]:
# Solution 2

import numpy as np

matrix = np.random.randint(10, 100, size=(4, 4))

print(matrix)

[[98 36 75 51]
 [75 51 65 80]
 [12 68 34 62]
 [44 56 84 63]]


In [3]:
# Solution 3

random_values = np.random.rand(6)

print(random_values)

[0.73147891 0.41788975 0.16638446 0.11131309 0.40755096 0.27913458]


In [5]:
# Solution 4

cities = np.array([
    "Madrid",
    "Paris",
    "London",
    "Rome",
    "Berlin",
    "Lisbon"
])

selected_cities = np.random.choice(cities, size=5)

print(selected_cities)

['Berlin' 'Rome' 'Lisbon' 'Paris' 'Berlin']


In [6]:
# Challenge Solution

daily_sales = np.random.randint(500, 2001, size=30)

print(daily_sales)

[1054  625 1917 1926 1716  876 1315 1198 1115 1549 1218 1381 1894  531
 1340 1341 1948 1962 1224 1768 1426 1769 1127  635 1316 1849  609 1495
 1548  633]


###  Why use `np.random.seed()`?

Without setting a seed, NumPy generates different random values every time the code is executed.

Setting a seed makes the results reproducible, which is especially useful when sharing notebooks, debugging code or comparing results.