# 1. Array Properties

NumPy arrays contain useful attributes that allow us to understand their structure and characteristics.

These properties are essential when working with datasets because they help us identify the dimensions, size and data types before performing any analysis.

In [4]:
import numpy as np

# Create a sales dataset

sales = np.array([
    [120, 135, 150, 160],
    [98, 110, 125, 140],
    [200, 220, 240, 260]
])

print(sales)

[[120 135 150 160]
 [ 98 110 125 140]
 [200 220 240 260]]


## Shape

The `shape` attribute returns the dimensions of an array.

It tells us the number of rows and columns in a two-dimensional array.

The result is returned as a tuple.

In [5]:
sales.shape

(3, 4)

The array contains:

- 3 rows
- 4 columns

Therefore, the total structure is 3 × 4.

## Size

The `size` attribute returns the total number of elements contained in an array.

In [6]:
sales.size

12

The array contains 12 values because:

3 rows × 4 columns = 12 elements

## Number of dimensions (`ndim`)

The `ndim` attribute returns the number of dimensions of an array.

Examples:

- 1 dimension → vector
- 2 dimensions → matrix
- 3 dimensions → multidimensional array

In [7]:
sales.ndim

2

In [8]:
one_dimension = np.array([10, 20, 30])

three_dimensions = np.array([
    [
        [1, 2],
        [3, 4]
    ]
])

print(one_dimension.ndim)

print(three_dimensions.ndim)

1
3


## Data type (`dtype`)

The `dtype` attribute shows the data type stored inside the array.

Common NumPy data types:

- `int` → integers
- `float` → decimal numbers
- `bool` → True/False values
- `str` → text values

In [9]:
sales.dtype

dtype('int32')

In [10]:
prices = np.array([
    19.99,
    25.50,
    32.75
])

prices.dtype

dtype('float64')

## Memory usage

NumPy arrays are efficient because they store data in a compact way.

- `itemsize` returns the size in bytes of each element.
- `nbytes` returns the total memory used by the array.

---

##  Practice Exercises

### Exercise 1

Create a NumPy array representing the monthly revenue of a company for one year.

Check:

- shape
- size
- number of dimensions
- data type


In [ ]:
# Write your solution here

### Exercise 2

Create a 3-dimensional array representing:

- 2 regions
- 3 stores
- 4 months

Check its dimensions using ndim and shape.


In [ ]:
# Write your solution here

### Exercise 3

Create an array containing product prices:

[12.99, 15.50, 20.75, 30.00]

Check its data type.


In [ ]:
# Write your solution here

### Challenge

A company stores customer information in an array:

- 5 customers
- 3 attributes:
    - age
    - purchases
    - visits

Create the array and analyze its structure.

## Solutions

In [3]:
# Solution 1

import numpy as np

revenue = np.array([
    12000,
    13500,
    14000,
    15500,
    16000,
    17000,
    18000,
    19000,
    21000,
    22000,
    23500,
    25000
])

print(revenue.shape)
print(revenue.size)
print(revenue.ndim)
print(revenue.dtype)


(12,)
12
1
int32


In [5]:
# Solution 2

regions = np.random.randint(
    100,
    500,
    size=(2,3,4)
)

print(regions)
print(regions.shape)
print(regions.ndim)

[[[308 458 251 243]
  [272 334 291 337]
  [294 240 451 322]]

 [[275 265 402 169]
  [299 359 447 135]
  [329 384 245 299]]]
(2, 3, 4)
3


In [6]:
# Solution 3

prices = np.array([
    12.99,
    15.50,
    20.75,
    30.00
])

print(prices.dtype)

float64


In [7]:
# Challenge solution

customers = np.array([
    [25, 12, 8],
    [34, 20, 15],
    [41, 8, 5],
    [29, 15, 10],
    [52, 30, 22]
])

print(customers.shape)
print(customers.size)
print(customers.ndim)

(5, 3)
15
2


### Key Takeaways

Before analyzing any dataset, it is important to understand its structure.

NumPy provides useful attributes:

- `shape` → dimensions of the array
- `size` → total number of elements
- `ndim` → number of dimensions
- `dtype` → data type of the elements

These concepts are fundamental when working with larger datasets and libraries such as Pandas.

# 2. Indexing

Indexing allows us to access individual elements from a NumPy array.

The indexing system in NumPy is similar to Python lists:

- Indexing starts at 0.
- Negative indexes can be used to access elements from the end.

In [8]:
import numpy as np

sales = np.array([120, 135, 150, 160, 180])

print(sales)

[120 135 150 160 180]


### 1D Array Indexing

In [11]:
sales[0]

120

In [12]:
sales[-1]

180

In NumPy:

- `array[0]` → first element
- `array[-1]` → last element

### 2D Array Indexing

In [13]:
monthly_sales = np.array([
    [120, 135, 150],
    [200, 220, 250],
    [90, 110, 130]
])

print(monthly_sales)

[[120 135 150]
 [200 220 250]
 [ 90 110 130]]


In [14]:
monthly_sales[1,2]

250

The first index represents the row.

The second index represents the column.

`array[row, column]`

In [15]:
monthly_sales[0]

array([120, 135, 150])

In [16]:
monthly_sales[:,1]

array([135, 220, 110])

The colon `:` means "select all values".

Example:

`array[:,1]`

means:

- all rows
- column with index 1

### 3D Array Indexing

In [17]:
sales_3d = np.array([
    [
        [120,130],
        [140,150]
    ],
    [
        [200,220],
        [240,260]
    ]
])

print(sales_3d)

[[[120 130]
  [140 150]]

 [[200 220]
  [240 260]]]


In [18]:
sales_3d[0]

array([[120, 130],
       [140, 150]])

In [19]:
sales_3d[1,0,1]

220

For 3D arrays:

array[dimension, row, column]


# 3. Slicing

Similar to Python lists, NumPy arrays allow us to access individual elements using square brackets `[]`.

NumPy also supports **slicing**, which allows us to extract portions of an array and create subarrays.

The general slicing syntax is:

```python
array[start:stop:step]
```

Where:

- `start` → the index where the slice begins (included).
- `stop` → the index where the slice ends (excluded).
- `step` → the interval between selected elements.

If any of these values are not specified, NumPy uses the default values:

- `start = 0`
- `stop = size of the dimension`
- `step = 1`

Slicing works with one-dimensional arrays as well as multi-dimensional arrays, allowing us to select specific rows, columns, or sections of a dataset.

In [21]:
sales = np.array([100,200,300,400,500])

sales[1:4]

array([200, 300, 400])

---

##  Practice Exercises

### Exercise 1

Given the following sales array:

[250, 300, 280, 350, 400]

Access:

- first value
- last value
- third value

In [ ]:
# Write your solution here

### Exercise 2

Given a store sales matrix:

Create code to obtain:

- first store sales
- second month sales
- last column

In [ ]:
# Write your solution here

### Exercise 3

Create a 3D array representing:

- 2 stores
- 3 products
- 4 weeks

Access the sales of:

Store 2,
Product 1,
Week 3


In [ ]:
# Write your solution here

### Challenge

A company has the following customer ages:

[22, 35, 28, 41, 30, 26]

Extract:

- first three customers
- last two customers
- every second customer

## Solutions

In [27]:
# Solution 1

sales = np.array([250, 300, 280, 350, 400])

first_value = sales[0]
last_value = sales[-1]
third_value = sales[2]

print(f"First value: {first_value}")
print(f"Last value: {last_value}")
print(f"Third value: {third_value}")

First value: 250
Last value: 400
Third value: 280


In [32]:
# Solution 2

stores_sales = np.array([
    [120, 135, 150],
    [200, 220, 250],
    [90, 110, 130]
])

# First store sales (first row)
first_store = stores_sales[0]

# Second month sales (second column)
second_month = stores_sales[:,1]

# Last column
last_column = stores_sales[:,-1]

print(f"First store sales: {first_store}")
print(f"\nSecond month sales: {second_month}")
print(f"\nLast column: {last_column}")


First store sales: [120 135 150]

Second month sales: [135 220 110]

Last column: [150 250 130]


In [33]:
# Solution 3

sales_3d = np.array([
    [
        [120, 130, 140, 150],
        [80, 90, 100, 110],
        [200, 220, 240, 260]
    ],
    [
        [150, 160, 170, 180],
        [95, 105, 115, 125],
        [250, 270, 290, 310]
    ]
])


store_2_product_1_week_3 = sales_3d[1,0,2]


print(store_2_product_1_week_3)

170


In [36]:
# Challenge Solution

customer_ages = np.array([
    22,
    35,
    28,
    41,
    30,
    26
])

# First three customers
first_three = customer_ages[:3]


# Last two customers
last_two = customer_ages[-2:]


# Every second customer
every_second = customer_ages[::2]


print("First three:")
print(first_three)

print("\nLast two:")
print(last_two)

print("\nEvery second customer:")
print(every_second)

First three:
[22 35 28]

Last two:
[30 26]

Every second customer:
[22 28 30]


## Key Takeaways

NumPy indexing allows us to access and manipulate specific parts of an array.

Main concepts:

- `array[index]` → access a single element
- `array[row, column]` → access elements in 2D arrays
- `:` → select all values in a dimension
- Negative indexes → access elements from the end
- Slicing → extract subsets of data

These concepts are essential for data manipulation and are the foundation for working with Pandas DataFrames.