# 1. Array Operations

NumPy allows us to perform mathematical operations directly on arrays.

These operations are vectorized, meaning that calculations are applied to all elements at once without the need for explicit loops.

This makes NumPy much faster and more efficient than traditional Python lists.

### Import Numpy and create arrays

In [60]:
import numpy as np

sales_january = np.array([120, 150, 170, 200])

sales_february = np.array([130, 160, 180, 220])

sales_january

array([120, 150, 170, 200])

## Addition and subtraction

NumPy performs operations element by element.

When two arrays have the same shape, the first element is operated with the first element, the second with the second, and so on.

In [61]:
# Addition

total_sales = sales_january + sales_february

print(total_sales)

[250 310 350 420]


In [62]:
# Subtraction

difference = sales_february - sales_january

print(difference)

[10 10 10 20]


## Multiplication and division

Multiplication and division are also performed element by element.

In [63]:
# multiplication

products = np.array([10, 20, 30])

prices = np.array([5, 8, 12])


revenue = products * prices

print(revenue)

[ 50 160 360]


In [64]:
# division

average_price = revenue / products

print(average_price)

[ 5.  8. 12.]


## Operations with scalars

A scalar is a single value.

NumPy automatically applies the operation to every element in the array.

In [65]:
sales = np.array([100, 200, 300])

sales * 2

array([200, 400, 600])

In [66]:
discount = sales * 0.9

discount

array([ 90., 180., 270.])

This operation applies a 10% discount to every value in the array.

## Vectorized operations

Vectorization allows us to perform calculations on entire arrays instead of using loops.

Example:

Traditional Python:

In [67]:
sales = [100, 200, 300]

new_sales = []

for value in sales:
    new_sales.append(value * 2)

print(new_sales)

[200, 400, 600]


With NumPy:

In [68]:
sales_array = np.array([100, 200, 300])

sales_array * 2

array([200, 400, 600])

## Mathematical functions

NumPy provides many mathematical functions that can be applied directly to arrays.

### Square root

In [69]:
numbers = np.array([1, 4, 9, 16])

np.sqrt(numbers)

array([1., 2., 3., 4.])

### Exponential

In [70]:
np.exp(numbers)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

### Absolute values

In [71]:
values = np.array([-5, -10, 15])

np.abs(values)

array([ 5, 10, 15])

### Power

In [72]:
np.power(numbers, 2)

array([  1,  16,  81, 256], dtype=int32)

---

##  Practice Exercises

### Exercise 1

Create two arrays representing sales from two stores.

Calculate the total sales.

In [73]:
# Write your solution here

### Exercise 2

A company has product quantities and prices:

quantities = [5, 10, 15]

prices = [20, 30, 25]

Calculate the total revenue for each product.

In [74]:
# Write your solution here

### Exercise 3

Apply a 15% discount to the following prices:

prices = [100, 250, 300, 450]

In [75]:
# Write your solution here

### Exercise 4

Calculate the square root of:

numbers = [25, 36, 49, 64]

In [76]:
# Write your solution here

### Challenge

A company has daily sales for 7 days:

[120, 150, 135, 180, 200, 175, 210]

Calculate:

- sales after a 5% increase
- difference between original and new sales

## Solutions

In [77]:
# Solution 1

import numpy as np

store_a = np.array([120, 150, 180])

store_b = np.array([100, 160, 200])

total_sales = store_a + store_b

print(total_sales)

[220 310 380]


In [78]:
# Solution 2

quantities = np.array([5, 10, 15])

prices = np.array([20, 30, 25])


revenue = quantities * prices

print(revenue)

[100 300 375]


In [79]:
# Solution 3

prices = np.array([100, 250, 300, 450])

discounted_prices = prices * 0.85

print(discounted_prices)

[ 85.  212.5 255.  382.5]


In [80]:
# Solution 4

numbers = np.array([25, 36, 49, 64])

print(np.sqrt(numbers))

[5. 6. 7. 8.]


In [81]:
# Challenge Solution

sales = np.array([
    120,
    150,
    135,
    180,
    200,
    175,
    210
])


new_sales = sales * 1.05

difference = new_sales - sales


print(new_sales)

print(difference)

[126.   157.5  141.75 189.   210.   183.75 220.5 ]
[ 6.    7.5   6.75  9.   10.    8.75 10.5 ]


### Key Takeaways

NumPy operations are based on vectorization:

- Arrays can be added, subtracted, multiplied and divided directly.
- Operations are performed element by element.
- Scalars are automatically applied to all values.
- Vectorized operations improve performance and make code cleaner.

This concept is fundamental for data analysis because real datasets usually contain thousands or millions of values.

# 2. Statistical Operations

NumPy provides several functions to perform basic statistical analysis on numerical data.

These functions are commonly used during Exploratory Data Analysis (EDA) to understand datasets and identify patterns.

### Sum

In [82]:
sales = np.array([120, 150, 170, 200, 180])

total_sales = np.sum(sales)

print(total_sales)

820


`np.sum()` calculates the total value of all elements in an array.

### Mean (Average)

In [83]:
average_sales = np.mean(sales)

print(average_sales)

164.0


The mean represents the average value of a dataset.

It is calculated by dividing the total sum by the number of elements.

### Median

In [84]:
median_sales = np.median(sales)

print(median_sales)

170.0


The median represents the middle value of a dataset when the values are sorted.

Unlike the mean, the median is less affected by extreme values (outliers).

### Minimum and Maximum

In [85]:
minimum = np.min(sales)

maximum = np.max(sales)

print(minimum)
print(maximum)

120
200


### Standard Deviation

In [86]:
std_sales = np.std(sales)

std_sales

27.27636339397171

Standard deviation measures how spread out the values are around the mean.

A low standard deviation means that values are close to the average.

A high standard deviation indicates greater variability.

### Variance

In [87]:
variance_sales = np.var(sales)

print(variance_sales)

744.0


Variance measures the average squared difference between each value and the mean.

It is related to standard deviation:

Standard deviation = √variance

### Percentiles

In [88]:
prices = np.array([10, 20, 30, 40, 50, 60, 70])


np.percentile(prices, 50)

40.0

Percentiles indicate the value below which a given percentage of observations fall.

Examples:

- 50th percentile → median
- 25th percentile → first quartile
- 75th percentile → third quartile

### Correlation

In [89]:
advertising = np.array([10,20,30,40,50])

sales = np.array([100,150,200,250,300])


correlation = np.corrcoef(advertising, sales)

print(correlation)

[[1. 1.]
 [1. 1.]]


Correlation measures the relationship between two variables.

Values close to:

- 1 → strong positive relationship
- 0 → no linear relationship
- -1 → strong negative relationship

---

##  Practice Exercises

### Exercise 1

Given the following daily sales:

[120, 135, 150, 160, 125, 140, 130]

Calculate:

- total sales
- average sales
- minimum value
- maximum value

In [ ]:
# Write your solution here

### Exercise 2

Calculate the standard deviation and variance of:

[20, 25, 30, 35, 40]

In [ ]:
# Write your solution here

### Exercise 3

A company tracks website visits:

[1200, 1500, 1800, 2000, 2500]

Calculate:

- mean visits
- median visits
- 75th percentile

In [ ]:
# Write your solution here

### Challenge

A company tracks website visits:

[1200, 1500, 1800, 2000, 2500]

Calculate:

- mean visits
- median visits
- 75th percentile

In [ ]:
# Write your solution here

## Solutions

In [90]:
# Solution 1

import numpy as np

daily_sales = np.array([120, 135, 150, 160, 125, 140, 130])

total_sales = np.sum(daily_sales)
average_sales = np.mean(daily_sales)
minimum_sales = np.min(daily_sales)
maximum_sales = np.max(daily_sales)

print("Total sales:", total_sales)
print("Average sales:", average_sales)
print("Minimum sales:", minimum_sales)
print("Maximum sales:", maximum_sales)


Total sales: 960
Average sales: 137.14285714285714
Minimum sales: 120
Maximum sales: 160


In [91]:
# Solution 2

values = np.array([20, 25, 30, 35, 40])

standard_deviation = np.std(values)
variance = np.var(values)

print("Standard deviation:", standard_deviation)
print("Variance:", variance)

Standard deviation: 7.0710678118654755
Variance: 50.0


In [92]:
# Solution 3

website_visits = np.array([1200, 1500, 1800, 2000, 2500])

mean_visits = np.mean(website_visits)
median_visits = np.median(website_visits)
percentile_75 = np.percentile(website_visits, 75)

print("Mean:", mean_visits)
print("Median:", median_visits)
print("75th percentile:", percentile_75)

Mean: 1800.0
Median: 1800.0
75th percentile: 2000.0


In [93]:
# Challenge Solution

revenue = np.array([
    12000,
    15000,
    14000,
    18000,
    25000,
    16000
])


average_revenue = np.mean(revenue)
revenue_variability = np.std(revenue)
highest_month = np.max(revenue)
lowest_month = np.min(revenue)
median_revenue = np.percentile(revenue, 50)


print("Average revenue:", average_revenue)
print("Standard deviation:", revenue_variability)
print("Highest revenue:", highest_month)
print("Lowest revenue:", lowest_month)
print("Median revenue:", median_revenue)

Average revenue: 16666.666666666668
Standard deviation: 4149.96653266291
Highest revenue: 25000
Lowest revenue: 12000
Median revenue: 15500.0
