# 1. Array Manipulation

NumPy allows us to modify the structure of arrays without changing the data itself.

These operations are useful when preparing datasets, transforming data structures and organizing information before analysis.

## Reshape 

The `reshape()` method changes the dimensions of an array while keeping the same values.

The total number of elements must remain the same.

In [1]:
import numpy as np

sales = np.array([100, 150, 200, 250, 300, 350])

print(sales)

[100 150 200 250 300 350]


In [2]:
sales_matrix = sales.reshape(2,3)

sales_matrix

array([[100, 150, 200],
       [250, 300, 350]])

The original array has 6 elements.

It can be transformed into:

- 2 rows × 3 columns
- 3 rows × 2 columns

but not into 4 × 2 because the number of elements would change.

## Flatten

The `flatten()` method converts a multidimensional array into a one-dimensional array.

In [3]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])


flat_array = matrix.flatten()

print(flat_array)

[1 2 3 4 5 6]


## Transpose

The `transpose()` method switches rows and columns.

It is commonly used when working with matrices and datasets.

In [4]:
sales = np.array([
    [100,200,300],
    [400,500,600]
])


sales.transpose()

array([[100, 400],
       [200, 500],
       [300, 600]])

## Concatenate

`np.concatenate()` joins multiple arrays together.

In [5]:
store_a = np.array([100,150,200])

store_b = np.array([120,180,220])


combined_sales = np.concatenate((store_a, store_b))

print(combined_sales)

[100 150 200 120 180 220]


## Split arrays

The `np.split()` function divides an array into multiple smaller arrays.

The split must be possible according to the number of elements.

This operation is useful when separating datasets into different groups.

In [2]:
import numpy as np

sales = np.array([100, 150, 200, 250, 300, 350])

parts = np.split(sales, 3)

print(parts)

[array([100, 150]), array([200, 250]), array([300, 350])]


In [3]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])


np.split(matrix, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

## Append

The `np.append()` function adds new elements to the end of an array.

Unlike Python lists, NumPy arrays have a fixed size, so append creates a new array.

In [4]:
products = np.array([10,20,30])

updated_products = np.append(products, 40)

print(updated_products)

[10 20 30 40]


## Insert

The `np.insert()` function adds values at a specific position.

In [5]:
products = np.array([10,20,30])

new_products = np.insert(products, 1, 15)

print(new_products)

[10 15 20 30]


The value `15` was inserted at index 1.

## Delete

The `np.delete()` function removes an element from an array using its index.

In [6]:
products = np.array([10,20,30,40])

remaining_products = np.delete(products, 2)

print(remaining_products)

[10 20 40]


## Working with axes

In multidimensional arrays, operations can be performed by rows or columns using the `axis` parameter.

- axis=0 → operate vertically (columns)
- axis=1 → operate horizontally (rows)

In [13]:
sales = np.array([
    [100,200,300],
    [150,250,350],
    [200,300,400]
])

sum_columns = np.sum(sales, axis=0)
sum_rows = np.sum(sales, axis=1)

print(sum_columns)
print(sum_rows)

[ 450  750 1050]
[600 750 900]


---

##  Practice Exercises

### Exercise 1

Create an array containing numbers from 1 to 12.

Transform it into:

- a 3x4 matrix
- a 4x3 matrix

In [ ]:
# Write your solution here  

### Exercise 2

Given the following matrix:

[
[1,2,3],
[4,5,6]
]

Convert it into a one-dimensional array.

In [ ]:
# Write your solution here  

### Exercise 3

A company has sales from two branches:

Branch A:
[120,150,180]

Branch B:
[200,220,250]

Combine both arrays.


In [ ]:
# Write your solution here  

### Exercise 4

Divide the following array into 4 equal parts:

[10,20,30,40,50,60,70,80]

In [ ]:
# Write your solution here  

### Challenge

Given the monthly sales:

[
[100,150,200],
[120,160,220],
[140,170,250]
]

Calculate:

- total sales per month
- total sales per store

## Solutions

In [17]:
# Solution 1

numbers = np.arange(1,13)

matrix_3x4 = numbers.reshape(3,4)
matrix_4x3 = numbers.reshape(4,3)


print(numbers)
print(matrix_3x4)
print(matrix_4x3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# Solution 2

matrix = np.array([
    [1,2,3],
    [4,5,6]
])

flat = matrix.flatten()

print(flat)

[1 2 3 4 5 6]


In [19]:
# Solution 3

branch_A = np.array([120,150,180])

branch_B = np.array([200,220,250])

all_sales = np.concatenate((branch_A, branch_B))

print(all_sales)



[120 150 180 200 220 250]


In [20]:
# Solution 4

values = np.array([10,20,30,40,50,60,70,80])

parts = np.split(values, 4)

print(parts)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]


In [22]:
# Challenge Solution

monthly_sales = np.array([
[100,150,200],
[120,160,220],
[140,170,250]
])

sales_per_month = np.sum(monthly_sales, axis=0)
sales_per_store = np.sum(monthly_sales, axis=1)

print(f"Monthly sales: {sales_per_month}")
print(f"Store sales : {sales_per_store}")

Monthly sales: [360 480 670]
Store sales : [450 500 560]


## Key Takeaways

Array manipulation allows us to transform and organize data efficiently.

Main operations:

- `reshape()` → change array dimensions
- `flatten()` → convert arrays into one dimension
- `transpose()` → switch rows and columns
- `concatenate()` → combine arrays
- `split()` → divide arrays
- `append()`, `insert()`, `delete()` → modify array contents

These operations are essential when preparing datasets for analysis.